# Generated by Django 5.2.13 on 2026-05-05 12:54

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_admission_public_dni_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailpreference',
            name='event_preferences',
            field=models.JSONField(blank=True, default=notifications.models.default_event_preferences),
        ),
    ]
