# Generated by Django 5.2.14 on 2026-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_systemsettings_enrollment_charges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Configuración del sistema', 'verbose_name_plural': 'Configuración del sistema'},
        ),
        migrations.AlterField(
            model_name='useremailpreference',
            name='delivery_channel',
            field=models.CharField(choices=[('profile', 'Solo perfil'), ('email', 'Email only'), ('both', 'Perfil y correo electrónico')], default='both', max_length=12),
        ),
    ]
