# Generated by Django 5.2.14 on 2026-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_systemsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admission_waitlist_grace_days',
            field=models.PositiveIntegerField(default=7, help_text='Días de gracia para que un admitido en lista de espera complete la matrícula.'),
        ),
    ]
