# Generated by Django 5.2.14 on 2026-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_allow_repeat_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('tel', 'Teléfono'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('file_upload', 'File Upload'), ('career_select', 'Career Select'), ('subject_select', 'Subject Select'), ('stripe_payment', 'Pago con Stripe'), ('info', 'Info')], max_length=30),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='stripe_payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Fallido')], max_length=20),
        ),
    ]
