# Generated by Django 5.2.15 on 2026-06-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
