# Generated by Django 5.2.13 on 2026-05-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_subject_credit_attempt_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['code', 'name']},
        ),
    ]
