# Generated by Django 5.2.14 on 2026-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_class_is_generated_by_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='schedulingconstraint',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
