# Generated by Django 5.2.12 on 2026-06-10

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_drop_teachersubjecteligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='show_final_grade_to_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='passing_grade',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Nota mínima para superar la asignatura (0.00–10.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
