# Generated by Django 5.2.15 on 2026-06-11 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_subject_unavailable_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingconstraint',
            name='run',
        ),
        migrations.RemoveField(
            model_name='schedulingconstraint',
            name='subject',
        ),
        migrations.AddField(
            model_name='schedulingconstraint',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_constraints', to='academic.career'),
        ),
        migrations.AlterField(
            model_name='department',
            name='teacher',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 't'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedulingconstraint',
            name='kind',
            field=models.CharField(choices=[('teacher_unavailable', 'Teacher unavailable'), ('classroom_unavailable', 'Classroom unavailable'), ('career_unavailable', 'Career unavailable')], max_length=24),
        ),
    ]
