# Generated by Django 5.2.14 on 2026-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_enrollmentfee_payment_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('exempted', 'Exempted'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
    ]
